export {
    IconHome2 as IconHome,
    IconDeviceGamepad2 as IconStore,
    IconBuildingStore as IconMarketplace,
    IconBooks as IconLibrary,
    IconSettings2 as IconEngine,
    IconAdjustments as IconSettings,
    IconUser,
    IconPlayerPlay as IconPlay,
    IconDownload,
    IconTrash,
    IconSearch,
    IconChevronDown as IconChevron,
    IconFolder,
    IconCheck,
    IconArrowRight,
    IconStar,
    IconStarFilled,
    IconBrandGithub,
    IconBrandYoutube,
    IconBrandDiscord,
} from '@tabler/icons-solidjs';
